spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: staging

---
spring:
  config:
    activate:
      on-profile: production