# commons (공통)
spring:
  profiles:
    include:
      - infrastructure
      - domain
      - core
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

---
# dev (서버 개발)
spring:
  config:
    activate:
      on-profile: dev

---
# production (실제 운영)
spring:
  config:
    activate:
      on-profile: production