# commons (공통)
server:
  port: 4040

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    include:
      - infrastructure
      - domain
      - common
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
---
# dev (서버 개발)
spring:
  config:
    activate:
      on-profile: dev

---
# production (실제 운영)
spring:
  config:
    activate:
      on-profile: production